# Generated by Django 5.0.2 on 2024-03-30 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nr', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(help_text='Customer Name', unique=True)),
                ('balance', models.IntegerField(null=True)),
                ('credits', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.customer')),
            ],
            options={
                'db_table': 'credits',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(choices=[('payin', 'Pay In'), ('payout', 'Pay Out'), ('transfer', 'Transfer')])),
                ('amount', models.IntegerField(null=True)),
                ('before', models.IntegerField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_customer', to='Bank.customer')),
                ('related', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_related', to='Bank.customer')),
            ],
            options={
                'db_table': 'actions',
            },
        ),
    ]
