# Generated by Django 5.0.2 on 2024-03-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nr', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.TextField(choices=[('payin', 'Pay In'), ('payout', 'Pay Out'), ('transfer', 'Transfer')])),
                ('amount', models.IntegerField()),
                ('related_nr', models.IntegerField(null=True)),
                ('before', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nr', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('balance', models.IntegerField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
