"""Django Module(s)"""
from django.db import migrations, models

# Generated by Django 4.2.6 on 2023-10-06 14:22

class Migration(migrations.Migration):
    """Migration"""
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr', models.IntegerField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('actiontype', models.TextField(choices=[('payin', 'Pay In'),
                                                         ('payout', 'Pay Out'),
                                                         ('transferI', 'Transfer In'),
                                                         ('transferO', 'Transfer Out')]
                                                         )),
                ('amount', models.FloatField()),
                ('related_nr', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nr', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('saldo', models.FloatField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
