# Generated by Django 4.2.6 on 2023-12-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.TextField(choices=[('payin', 'Pay In'), ('payout', 'Pay Out'), ('transfer', 'Transfer')])),
                ('amount', models.FloatField()),
                ('related_nr', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nr', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
