# Generated by Django 4.2.2 on 2023-07-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nr', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('saldo', models.FloatField()),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr', models.IntegerField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('actiontype', models.TextField()),
                ('betrag', models.FloatField()),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actions.action')),
            ],
            options={
                'db_table': 'actions',
            },
        ),
    ]
